version: "3.7"
services:
  tacodns:
    container_name: tacodns
    image: handz/tacodns
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./config.yml:/etc/tacodns.yml
